[package]
name = "buffer-sample"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.38"
cpal = "0.15.3"
eframe = "0.28.1"
egui = "0.28.1"
egui-winit = "0.28.1"
ferris-says = "0.3.1"
hound = "3.5.1"
rfd = "0.14.1"
winit = "0.30.5"
